### PR TITLE
fix(BS-14507) case overview duplicates information of overview section

### PR DESCRIPTION
**Pull request by cpuy**
* Rename first tab from "Context" to "Case"
* Remove all sections but Case Overview from "Case" tab
* Remove the section title "Case Overview" as it is the only section available
* Have Form tab be the first and selected by default

To be done: Add a "Go to case details" link above the Case overview

Fixes [BS-1450](https://bonitasoft.atlassian.net/browse/BS-14507)

### CODE REVIEW

**Comment by abirembaut** [comment]
Maybe we can create a new Jira subtask for the "Go to case details" link, so that we can merge this PR

**Comment by abirembaut** [comment]
I think the tasks-modal-details module should also be removed and replaced by a tasks-modal-context for the popup mode.

**Comment by cpuy** [comment]
Subtask [BS-14931](https://bonitasoft.atlassian.net/browse/BS-14931) created.
Let me see this module things

**Comment by cpuy** [comment]
> I think the tasks-modal-details module should also be removed and replaced by a tasks-modal-context for the popup mode.

I don't understand what it is about. Could you be more precise please ?

**Comment by abirembaut** [comment]
I am talking about tasks-modal-details.js and tasks-modal-details.html which is displayed in a popup when you click on the right button in wide table mode. I think we should only display the case overview in the popup when you click on this right button.

**Comment by cpuy** [comment]
Indeed it is already the case since it is using the same directive
https://github.com/bonitasoft/bonita-portal-js/blob/master/main/features/user/tasks/list/tasks-modal-details.html#L8

Or I may misunderstand your point.

**Comment by abirembaut** [comment]
Indeed, but I believe we shouldn't display the tabs container in the popup. Just the content of the case tab. The form is already displayed when you click on the left button. It will look like both buttons do the same thing since the form is now the first tab.

**Comment by abirembaut** [comment]
I think that there is also some code that should be removed like the getHistory function in store.js

**Comment by cpuy** [comment]
> Indeed, but I believe we shouldn't display the tabs container in the popup. Just the content of the case tab. The form is already displayed when you click on the left button. It will look like both buttons do the same thing since the form is now the first tab. 

Sure you're right

> I think that there is also some code that should be removed like the getHistory function in store.js

I'll check that

**Comment by abirembaut** [comment]
Or maybe we should display the old history section if there is no overview form mapped on the process ? (Just a thought)

**Comment by abirembaut** [comment]
In addition, we shouldn't display the case tab in the details pane if there is no overview mapped. or at least display a message

**Comment by cpuy** [comment]
Reopen PR on tasklist branch

**Pull request closed without merging**
