### PR TITLE
From grunt to gulp

### PR DESCRIPTION
**Pull request by dhoko**

### CODE REVIEW

**Comment by cpuy** [comment]
@julien-reboul have you reviewed this PR ?

LGTM

**Comment by julien-reboul** [comment]
yes, no special return but I would need to work with it a bit before merging it

**Comment by cpuy** [comment]
ok so we don't merge it ?

2015-01-13 17:15 GMT+01:00 Julien <notifications@github.com>:

> yes, no special return but I would need to work with it a bit before
> merging it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bonitasoft/bonita-portal-js/pull/9#issuecomment-69770218>
> .
>



-- 
*Colin PUY*
*R&D Engineer*  colin.puy@bonitasoft.com
32, rue Gustave Eiffel - 38000 Grenoble, France
        <http://www.bonitasoft.com> <http://twitter.com/bonitasoft>
<https://www.facebook.com/bonitasoftbpm>
<http://www.linkedin.com/groups?gid=3182097>
<http://www.slideshare.net/BonitaSoft> <http://www.youtube.com/bonitasoft>
<http://www.bonitasoft.com/bos_redirect.php?bos_redirect_id=128>
This message and
any attachment (the "message") is intended solely for the addressees and is
confidential. If you receive this message by mistake, please delete it and
notify the sender immediately. Any use not in accordance with its purpose,
any out-spread or disclosure, either as a whole or partially, is prohibited
except with formal approval. Internet cannot guarantee the integrity of
this message, therefore Bonitasoft will not be liable for the message if
modified.

**Comment by julien-reboul** [comment]
maybe in MBF but not in master yet

**Comment by julien-reboul** [comment]
after test, it is fine on this module. 
However, I think we should not merge since bonita-portal-js-sp doesn't work properly with gulp

**Comment by julien-reboul** [comment]
I tested the development with gulp, the major issue I see is that the modification you make on a file has to be concat to the served file (template.html or app.js). However, these files are put in cache and I needed to empty the browser cache to see the modification. I did not succeed to have a livereload yet. Shouldn't the browsersync ease this?

**Comment by cpuy** [comment]
Weird, we have not this issue in page-builder. And also we use browsersync
that is really a must have.
@dhoko, any idea ?

2015-01-19 23:33 GMT+01:00 Julien <notifications@github.com>:

> I tested the development with gulp, the major issue I see is that the
> modification you make on a file has to be concat to the served file
> (template.html or app.js). However, these files are put in cache and I
> needed to empty the browser cache to see the modification. I did not
> succeed to have a livereload yet. Shouldn't the browsersync ease this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bonitasoft/bonita-portal-js/pull/9#issuecomment-70573191>
> .
>



-- 
*Colin PUY*
*R&D Engineer*  colin.puy@bonitasoft.com
32, rue Gustave Eiffel - 38000 Grenoble, France
        <http://www.bonitasoft.com> <http://twitter.com/bonitasoft>
<https://www.facebook.com/bonitasoftbpm>
<http://www.linkedin.com/groups?gid=3182097>
<http://www.slideshare.net/BonitaSoft> <http://www.youtube.com/bonitasoft>
<http://www.bonitasoft.com/bos_redirect.php?bos_redirect_id=128>
This message and
any attachment (the "message") is intended solely for the addressees and is
confidential. If you receive this message by mistake, please delete it and
notify the sender immediately. Any use not in accordance with its purpose,
any out-spread or disclosure, either as a whole or partially, is prohibited
except with formal approval. Internet cannot guarantee the integrity of
this message, therefore Bonitasoft will not be liable for the message if
modified.

**Comment by dhoko** [comment]
I'm building the server and will look at it. I don't understand why there are some issues.

**Comment by dhoko** [comment]
@julien-reboul "However, these files are put in cache" and that's why there is a cache buster to prevent it. 

```html
<script src="scripts/jQuery.vendor.js{{randomAppCache}}"></script>
<script src="scripts/angular.vendor.js{{randomAppCache}}"></script>
<script src="scripts/vendor.js{{randomAppCache}}"></script>

<script src="scripts/app-community.js{{randomAppCache}}"></script>
<script src="scripts/templates-community.js{{randomAppCache}}"></script>
```

**Comment by julien-reboul** [comment]
I know but I don't undestand I had to empty cache for the file to be reload properly...

**Pull request closed without merging**
